### ISSUE TITLE
Crear pantalla Administrar Clientes

### ISSUE THREAD

**Issue by raphapy** [owl-javase8-012016/owl-pos-app#2]
La pantalla debe presentar al usuario las opciones:
1. Crear Cliente
2. Editar Cliente
3. Eliminar Cliente
4. Volver

**Comment by raphapy** [comment]
Dario y Nelson, favor realizar el pull request para integrar su código al master

**Comment by raphapy** [comment]
Listo el merge

**Comment by migdar** [comment]
Al estar listo el merge, ya no hace falta realizar el pull request verdad?

**Comment by raphapy** [comment]
Así es. Saludos.
